name: cron

on:
  schedule:
    - cron: '0 0 * * 1-5'
    # 평일 한국 시간 9시

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyyaml
          pip install beautifulsoup4
          pip install pytz
      - name: Run Crawler
        run: |
          python etc/check.py 
        env:
          MESSAGE_URL: ${{ secrets.MESSAGE_URL }}
